<div id="videito" style="display:none;">
  <object width="800" height="530">
    <param name="movie" value="[field:lianjie/]">
    </param>
    <param name="allowFullScreen" value="true">
    </param>
    <param name="allowscriptaccess" value="always">
    </param>
    <embed src="[field:lianjie/]" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="800" height="530"></embed>
  </object>