<li> <a href="[field:arcurl/]" target="_blank"><img src="[field:img1/]" alt="[field:title/]" /></a> <a href="[field:arcurl/]" target="_blank">
        <h3>[field:cpyw/]</h3>
        </a> <a href="[field:arcurl/]" target="_blank">
        <h1>[field:title/]</h1>
        </a>
        <p>¥[field:jg/]</p>
        <h2>[field:ms/]</h2>
        <a href="[field:lj/]" class="buy" target="_blank">立即购买</a> </li>