<field:cpyw itemname="产品英文" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:cpyw>
<field:img1 itemname="产品主图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:img1>
<field:ms itemname="功效描述" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ms>
<field:cf itemname="所含成份" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:cf>
<field:sy itemname="使用方法" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sy>
<field:gg itemname="规格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:gg>
<field:cd itemname="产地" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:cd>
<field:jg itemname="价格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jg>
<field:lj itemname="产品购买链接" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lj>
<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
