<?php
$z[0]=Array("global","",48,74);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",101,123);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",166,188);
$z[2][4]['name']="cfg_add";
$z[3]=Array("global","",201,225);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",436,458);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",547,568);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("arclist","\r\n      <li class=\"yb_ercode\" style=\"height:53px;\">微信二维码 <br>\r\n        <img class=\"hd_qr\" src=\"[field:img2/]\" width=\"125\" alt=\"[field:title/]\"> </li>\r\n      ",670,940);
$z[6][4]['typeid']="25";
$z[6][4]['row']="1";
$z[6][4]['orderby']="pubdate";
$z[6][4]['addfields']="img2";
$z[6][4]['channelid']="17";

?>