<?php
$z[0]=Array("arclist"," <a href=\"[field:lianjie/]\"><img src=\"[field:img2/]\" /></a> ",22,199);
$z[0][4]['typeid']="24";
$z[0][4]['titlelen']="";
$z[0][4]['row']="1";
$z[0][4]['orderby']="";
$z[0][4]['addfields']="img2,lianjie";
$z[0][4]['channelid']="17";
$z[1]=Array("field","(@me==\"\")? @me=\" class='nav-a' \":@me=\"\";",283,373);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n      ",404,609);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='nav-a'>~typename~</a> </li>";

?>