<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",325,354);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",391,450);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1173,1208);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <li><a  href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n      ",1312,1540);
$z[5][4]['type']="son";
$z[5][4]['reid']="4";
$z[5][4]['row']="9";
$z[5][4]['currentstyle']="<li class='product-bk' ><a href='~typelink~'>~typename~</a> </li>";
$z[6]=Array("list","\r\n      <li> <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:img1/]\" alt=\"[field:title/]\" /></a> <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n        <h3>[field:cpyw/]</h3>\r\n        </a> <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n        <h1>[field:title/]</h1>\r\n        </a>\r\n        <p>¥[field:jg/]</p>\r\n        <h2>[field:ms/]</h2>\r\n        <a href=\"[field:lj/]\" class=\"buy\" target=\"_blank\">立即购买</a> </li>\r\n      ",1610,2091);
$z[6][4]['row']="6";
$z[6][4]['pagesize']="6";
$z[7]=Array("pagelist","",2163,2237);
$z[7][4]['istitem']="index,pre,next,pageno,end,option,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2294,2331);
$z[8][4]['filename']="footer.htm";

?>