<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",325,354);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",391,450);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1204,1239);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n<div class=\"news-ban\"><img  src=\"[field:img2/]\"  style=\"width:100%\" /></div>\r\n",1258,1442);
$z[5][4]['typeid']="22";
$z[5][4]['orderby']="pubdate";
$z[5][4]['addfields']="img2,lianjie";
$z[5][4]['channelid']="17";
$z[6]=Array("field","",1527,1556);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1573,1596);
$z[7][4]['name']="seotitle";
$z[8]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        ",1662,1783);
$z[8][4]['type']="sun";
$z[9]=Array("list","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a>\r\n        <h6>[field:pubdate function=\"GetDateMK(@me)\"/] </h6>\r\n      </li>\r\n      ",1861,2045);
$z[9][4]['row']="8";
$z[9][4]['pagesize']="8";
$z[10]=Array("pagelist","",2115,2189);
$z[10][4]['istitem']="index,pre,next,pageno,end,option,";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",2244,2281);
$z[11][4]['filename']="footer.htm";

?>